### ISSUE TITLE
Co do zrobienia na dzisiejszym spotkaniu :P

### ISSUE THREAD

**Issue by quetz05** [WezSieTato/SRO#1]
Dla mnie:
1. Przeczytanie całej dokumentacji, sprawdzenie jej poprawności i sensu.
2. Dopisanie obsługi sytuacji awaryjnych.
3. Dopisanie brakujących informacji o projekcie.
4. Dopisanie wyników (haha) testów.

Dla Jarka:
1. Zaczarowanie, żeby Docker działał
2. Pomyślenie o prezentacji, co i jak
3. Załatwienie rzutnika

Dla Modzela:
1. Skończenie działania komunikacji w warstwie zewnętrznej - ma działać
2. Zasymulowanie przynajmniej jednej, DZIAŁAJĄCEJ sytuacji awaryjnej (tak, żeby ją zaprezentować)
3. Napisanie WSZYSTKICH testów (może być symulacja, dla jednej instancji serwera, tam gdzie się da, generalnie ma działać i muszą być tak zrobione, żeby Kruk mógł sobie je odtworzyć); możesz iść po lini najmniejszego oporu, byle tylko to działało (każdy z testów osobno, nie wszystkie na raz); ja już je opiszę w dokumentacji.

Dla Marcina:
1. Próba skończenia komunikacji w warstwie wewnętrznej
2. Zasymulowanie przynajmniej jednej, DZIAŁAJĄCEJ sytuacji awaryjnej (tak, żeby ją zaprezentować)
3. Sterowanie redundancją (może być w najprostszej postaci i na przykładzie dwóch serwerów)
4. Synchronizacja w przypadku awarii serwera wewnętrznego (w sensie następuje synchronizacja i nagle odłączył się węzeł warstwy węwnętrznej - co robić?) - tego nie ma w dokumentacji, właśnie ją przeczytałem całą :smiling_imp: 

Prośba DO WSZYSTKICH:
Przejrzenie wymagań i założeń i danie mi znać (np. wpisując w Issue, albo na maila) co jest zrobione, co będzie a czego NA PEWNO nie da się w żadnym stopniu zrobić.

Tak samo prosiłbym o sprawdzenie w dokumentacji swojej warstwy i upewnienie się, że informacje się zgadzają z tym co jest w kodzie (w szczególności informacje zawarte w Message'ach!)

EDIT:
Doopisałem rzeczy, którymi trzeba się zająć, mam nadzieję, jutro (bo dziś już wystarczająco dużo jest):

schamty kodu projektu
schemat bazy danych
sprawdzić czy wiadomości się zgadzają
sprawdzić czy plik konfiguracyjny się zgadza
ograniczenia i braki w systemie
sposób synchronizacji danych między warstwami
plan prezentacji

**Comment by WezSieTato** [comment]
Projekt zaliczony, elo.
